Fix spec-interp and ensure its tests pass
wasmjit-omr/wasmjit-omr pull request #32
Opened 2018-01-10 21:09 UTC by Leonardo2718

To avoid having the JIT interfere with the `spec-interp` tool, it is
unconditionally disabled for this tool. In addition, instance counting
is added to `wabt::jit::JitEnvironment` to ensure the JIT is only
initialized once.

Fixes #30

2018-01-11 15:51 UTC, Leonardo2718 commented
Build failures are not related to this change (see #34). This PR is ready for review @aviansie-ben.

2018-01-12 18:49 UTC, aviansie-ben requested changes

2018-01-12 18:49 UTC, aviansie-ben commented on src/jit/environment.cc
> +
This empty line should be removed.

2018-01-12 21:01 UTC, Leonardo2718 commented on src/jit/environment.cc
> +
Not sure how *that* happened 😛 . Fixed.

2018-01-13 00:45 UTC, aviansie-ben approved these changes
LGTM

2018-01-13 00:45 UTC, merged