Add basic script to measure JIT vs Interpreter execution time.
wasmjit-omr/wasmjit-omr pull request #44
Opened 2018-01-21 19:47 UTC by FatalDestiny

Added a basic script to compare the execution time of the JIT and the interpreter, tried to keep things as simple as possible. 

Takes a wasm text file + arguments as input, writes interpreter and JIT times to STDOUT along with a diff of their output if they differ. 

Closes #42

2018-01-24 10:07 UTC, aviansie-ben requested changes

2018-01-24 10:07 UTC, aviansie-ben commented on test/run-jit-perform.py
> +  parser.add_argument('--disable-jit', action='store_true')
This argument is never used and it would never make sense to pass it, so it should be removed.

2018-01-24 10:07 UTC, aviansie-ben commented on test/run-jit-perform.py
> +      find_exe.GetWat2WasmExecutable(options.bindir),
You seem to always be using the `wat2wasm` tool here. This breaks the `--spec` argument, which expects the `wast2json` tool to be used on its input.

2018-01-24 10:07 UTC, aviansie-ben commented on test/run-jit-perform.py
> +  with utils.TempDirectory(options.out_dir, 'run-interp-') as out_dir:
The name of the temporary directory should be changed to reflect the fact that we're running a JIT performance test, not an interpreter test.

2018-01-24 19:29 UTC, FatalDestiny commented on test/run-jit-perform.py
> +      find_exe.GetWat2WasmExecutable(options.bindir),
The spec interpreter doesn't work with the JIT anyway, so I'll remove the `--spec` option entirely.

2018-01-24 19:30 UTC, aviansie-ben requested changes
Your new commit has a subject line that is much too long. Please either shorten it or split it into multiple commits.

2018-01-25 06:10 UTC, aviansie-ben approved these changes

2018-01-25 06:11 UTC, merged