WIP: Print stack traces when a trap is encountered
wasmjit-omr/wasmjit-omr pull request #87
Opened 2018-03-12 19:51 UTC by aviansie-ben

This changeset introduces the ability for the interpreter to load debug names from WASM files and use them in order to print stack traces when trapping. This is mostly useful when debugging larger programs, since using the `--trace` option isn't feasible when doing so.

2018-03-12 22:17 UTC, aviansie-ben commented
All the known issues with this have now been worked out, so it should be ready for merging.

2018-03-14 01:30 UTC, aviansie-ben commented
Merge conflicts caused by merging #88 into master have been fixed.

@Leonardo2718 @FatalDestiny please review ASAP so this can get merged quickly. This changeset changes the implementation of nearly every opcode in the JIT very slightly, which will cause pretty bad merge conflicts with other PRs; the longer this gets left unmerged, the more nasty merge conflicts we'll have to deal with as a result.

2018-03-14 19:13 UTC, Leonardo2718 requested changes
Other than the one indentation problem, LGTM!

2018-03-14 19:13 UTC, Leonardo2718 commented on src/jit/function-builder.cc
> +  b->            Const(static_cast<Result_t>(interp::Result::TrapValueStackExhausted)),
I think this is indented incorrectly.

2018-03-14 19:15 UTC, FatalDestiny reviewed
LGTM, other than the indentation problem Leo noticed.

2018-03-14 19:26 UTC, aviansie-ben commented on src/jit/function-builder.cc
> +  b->            Const(static_cast<Result_t>(interp::Result::TrapValueStackExhausted)),
Nice catch. Should be fixed now.

2018-03-14 20:05 UTC, Leonardo2718 approved these changes

2018-03-14 20:06 UTC, merged