WIP: Implement some of the conversion opcodes
wasmjit-omr/wasmjit-omr pull request #88
Opened 2018-03-12 23:50 UTC by Leonardo2718

This changeset implements several of the WebAssembly type conversion opcodes.

Closes #79 
Closes #80 
Closes #81 
Closes #82 
Closes #83

2018-03-13 04:27 UTC, aviansie-ben requested changes
Other than some minor formatting issues, LGTM so far.

2018-03-13 04:27 UTC, aviansie-ben commented on src/jit/function-builder.cc
> +      b->            LoadAt(typeDictionary()->PointerTo(Int8), EmitMemoryPreAccess<int8_t>(b, &pc))));
Just a small nitpick, but the indentation is wrong on all your `UnsignedConvertTo`s for unsigned extending loads

2018-03-13 21:14 UTC, Leonardo2718 commented
@aviansie-ben I've corrected the indentation, pushed some additional opcode implementations, and removed the WIP.

Although there are no tests for these opcodes, we should go ahead and merge this PR so other work can move forward, which will act as testing for these opcodes.

2018-03-14 01:11 UTC, aviansie-ben approved these changes
LGTM. I'll merge without tests since this works in the raytracer, but please open issues for each group of opcodes you implemented to ensure that those tests don't get completely forgotten about.

2018-03-14 01:11 UTC, merged